### PR TITLE
use a boundary that does not exist in the pattern.

### PR DESCRIPTION
**Pull request by rmpel**
it's not pretty, I know
but it works and saved my ass more than once. 4 times to be precise :P

lots of room for improvement, but this gets the job done just fine.

### CODE REVIEW

**Comment by bbrala** [comment]
This whole repo is a "get the job done" thing ;)

Could you please adjust the code to not use implicit curly brackets? I really dislike that style since it is so prone to creating bugs.

**Comment by rmpel** [comment]
hehe, speaking of "getting the job done" :P

**Comment by rmpel** [comment]
Github tells me "Add more commits by pushing to the master branch on rmpel/php7-ereg-shim."
I did that, so now what? Wait? will it eventually get here? or do I need to do something to make my changed appear in this PR?

**Comment by bbrala** [comment]
Seems your commit had been added?

more readable code<https://github.com/bbrala/php7-ereg-shim/pull/2/commits/ae29d8d2e8f4d8cdb321925fb320229140597c09> - ae29d8d<https://github.com/bbrala/php7-ereg-shim/pull/2/commits/ae29d8d2e8f4d8cdb321925fb320229140597c09>

**Comment by bbrala** [comment]
Thanks!

**Comment by glensc** [comment]
1. This PR replaces https://github.com/bbrala/php7-ereg-shim/pull/1
2. This PR introduces another bug: https://github.com/bbrala/php7-ereg-shim/pull/3

**Comment by rmpel** [comment]
body, table, td, a { font-family: 'Open Sans', 'Trebuchet MS', Trebuchet, sans-serif !important; font-size: 12px; } table.footer tr td { vertical-align: bottom; white-space: nowrap; } table.footer tr td, table.footer tr td a { color: #0365dd; font-weight: 500; font-size: 18px; text-decoration: none; } table.footer tr td a a { line-height: 30px; }



(English below)

Geachte,

In verband met de feestdagen zijn wij tot aan de Kerst aanwezig met beperkte bezetting en vanaf de Kerst zijn wij gesloten.

Vanaf 4 januari zijn wij allen weer aanwezig.

In geval van nood, bijv. website offline, server problemen; bel ons op; 030 264 06 05.
Alle overige zaken zullen wij in het nieuwe jaar oppakken.

Wij wensen u hele fijne feestdagen!, doe voorzichtig met oliebollen (want vuurwerk zit er niet in dit jaar), en tot volgend jaar!

----

Dear,

Due to the holidays, we are out of office. We will be back on januari 4th.

In case of website-outage, server problems; breaking issues; please call us! 030 264 06 05.
All other questions will be answered next year.

We wish you all a Merry Christmas and a Happy New Year. Take care and see you next year!
Met vriendelijke groet,
With kind regards,
Remon Pel

In verband met de aanhoudende COVID-19 situatie werken wij zo veel mogelijk vanuit huis. Wij zijn en blijven zowel telefonisch als per e-mail bereikbaar via 030 264 06 05 / support@clearsite.nl en vragen u om e-mail als primair communicatiemiddel te gebruiken, tenzij uw vraag urgent is. Dank voor uw begrip.
Due to the continuing COVID-19 situation we work from home. We are and will remain available by phone and e-mail on 030 264 06 05 / support@clearsite.nl. We do ask to use e-mail as our primary contact method unless urgent. Thank you for understanding.



	
	
	



	 


	
	www.clearsite.nl | 030 264 06 05 | bekijk ons werk

**Pull request merged**
